name: Check build

on:
  pull_request:
  schedule:
    - cron:  0 20 * * 5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: docker build
      run: docker build -t cflow .
